In [197]:
import pandas as pd
import numpy as np

In [244]:
path = 'D:\\USER\\MRINMAY\\'
ipl= pd.read_csv(path+'ipl-matches.csv')
movie = pd.read_csv(path+'movies.csv')
mov = pd.read_csv(path+'movie_1000.csv')
IPL = pd.read_csv(path+'deliveries.csv')

In [199]:
# Applying builin aggregation function on groupby object
gen = movie.groupby('genres')

In [200]:
movie.head(0)

Empty DataFrame
Columns: [title_x, imdb_id, poster_path, wiki_link, title_y, original_title, is_adult, year_of_release, runtime, genres, imdb_rating, imdb_votes, story, summary, tagline, actors, wins_nominations, release_date]
Index: []

In [201]:
gen['imdb_rating'].mean().sort_values(ascending=False).head(1)

genres
Documentary|Sport    8.6
Name: imdb_rating, dtype: float64

In [202]:
gen['imdb_votes'].sum().sort_values(ascending=False).head()

genres
Comedy|Drama|Romance    868870
Comedy|Drama            819260
Drama|Romance           494742
Drama                   486525
Action|Crime|Drama      424406
Name: imdb_votes, dtype: int64

In [203]:
gen['imdb_rating'].max().sort_values(ascending=False).head(1)

genres
Action|Drama    9.4
Name: imdb_rating, dtype: float64

In [204]:
len(movie.groupby('actors'))

1617

In [205]:
movie.groupby('genres').nunique()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
genres,,,,,,,,,,,,,,,,,
Action,14,14,13,15,14,14,1,8,12,12,13,13,14,4,14,2,10
Action|Adventure,3,3,3,3,3,3,1,3,3,2,3,3,3,1,3,1,3
Action|Adventure|Animation,3,3,3,3,3,3,1,2,3,3,3,3,3,0,3,2,3
Action|Adventure|Comedy,11,11,11,11,11,11,1,8,11,10,11,11,11,4,11,6,11
Action|Adventure|Crime,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Romance|Thriller,4,4,4,4,4,4,1,3,3,4,4,3,4,0,4,1,2
Sci-Fi,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1
Sport,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1
Thriller,23,23,17,23,23,23,1,12,16,17,23,21,22,5,23,3,19
War,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1

In [206]:
movie.groupby('genres').size()

genres
Action                        15
Action|Adventure               3
Action|Adventure|Animation     3
Action|Adventure|Comedy       11
Action|Adventure|Crime         1
                              ..
Romance|Thriller               4
Sci-Fi                         1
Sport                          1
Thriller                      23
War                            1
Length: 205, dtype: int64

In [207]:
movie.groupby('genres').value_counts()

genres                   title_x                        imdb_id    poster_path                                                                                                                       wiki_link                                                    title_y                        original_title                 is_adult  year_of_release  runtime  imdb_rating  imdb_votes  story                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           summary                                                                                                                                                                                                             tagline                                             actors                                                                                                                                                                                                                wins_nominations          release_date
Action                   Ranbanka                       tt5151622  https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Ranbanka.jpg/220px-Ranbanka.jpg                                              https://en.wikipedia.org/wiki/Ranbanka                       Ranbanka                       Ranbanka                       0         2015             98       3.7          118         Rahul  an engineer  tries his best to protect his wife from a goon feared by all. The goon wants to marry Rahul's wife at any cost  and this doesn't bother him whether she is already married or she has a son. In the process  Rahul tries to take help from the law  but all efforts go awry  and the tables turn on him. When finally everything goes against him and his wife  he turns into an angry man  who is on a rampage to protect his wife by all means  even if it means killing the goon  and giving him the worst death he can ever wish for.                                                                                                                                                                                                   A non-violent engineer resorts to violence after his attempts to save his family from a local goon result in his son's murder.                                                                                      A Film By Aryeman                                   Manish Paul|Ravi Kishan|Pooja Thakur|Rudra Kaushik|Avya Agarwal|Avinash Dwivedi|                                                                                                                                      1 win                     6 November 2015 (India)    1
Action|Adventure|Comedy  Heroes (2008 film)             tt1114725  https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Heroes_Hindi_Film.jpg/220px-Heroes_Hindi_Film.jpg                            https://en.wikipedia.org/wiki/Heroes_(2008_film)             Heroes                         Heroes                         0         2008             139      5.6          1896        Havaldar Balkar Singh  Captain Dhananjay Shergill and Lieutenant Sahil Naqvi are amongst numerous fatalities on India's side in the 1999 Kargil war against Pakistan. All 3 men had written their last letters to Kuljeet Kaur  Squadron Leader Vikram Singh  and Dr. Naqvi respectively. These letters were located 3 years later by IBN Reporter  Avinash Sarin  who entrusts them to two Indore-based slackers  Ali Shah and Sameer Suri  and asks them to deliver them to Chandigarh  Manali  and Leh respectively. Ali and Sameer set out to film this journey in order to get a graduation degree so that they can re-locate to America as well as televise it widely in order to convince the youth not to join any of India's armed forces.             Two boys travel a thousand miles to deliver three letters as a part of their film school assignment. However  little do they know that the journey they have embarked upon will give a new meaning to their life.   Heroes are not born| but created by circumstances!  Sohail Khan|Vatsal Sheth|Amrita Arora|Riya Sen|Mohnish Bahl|Preity Zinta|Salman Khan|Dwij Yadav|Bobby Deol|Sunny Deol|Hrishitaa Bhatt|Dino Morea|Prateeksha Lonkar|Mithun Chakraborty|                                1 nomination              24 October 2008 (India)    1
Action|Adventure|Drama   Mirzya (film)                  tt4940456  https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Mirzya_poster.jpg/220px-Mirzya_poster.jpg                                    https://en.wikipedia.org/wiki/Mirzya_(film)                  Mirzya                         Mirzya                         0         2016             129      4.6          1581        A horse groom reconnects with his childhood love  but she is engaged to marry the local prince.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 A horse groom reconnects with his childhood love  but she is engaged to marry the local prince.                                                                                                                     Dare to love                                        Harshvardhan Kapoor|Saiyami Kher|Art Malik|Anuj Choudhry|Om Puri|K.K. Raina|                                                                                                                                          3 wins & 3 nominations    7 October 2016 (USA)       1
                         Raavan                         tt1334470  https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/Raavanposter2.jpg/220px-Raavanposter2.jpg                                    https://en.wikipedia.org/wiki/Raavan                         Raavan                         Raavan                         0         2010             130      5.4          3897        Ragini re-locates to distant Lal Matti along with her Superintendent of Police husband  Dev Pratap Sharma  in order to enable him to apprehend a bandit  Beera Munda. Shortly thereafter her life will be turned upside down when she will be abducted by Beera and held captive. It is during this captivity she will not only find out that her fate will be decided within 14 hours  but also the real reason behind her abduction.                                                                                                                                                                                                                                                                                                                          A bandit leader kidnaps the wife of the policeman who killed his sister  but later falls in love with her.                                                                                                          Not just a story| a world.                          Abhishek Bachchan|Aishwarya Rai Bachchan|Govinda|Vikram|Ajay Gehi|Ravi Kishan|Priyamani|Nikhil Dwivedi|                                                                                                               1 win & 2 nominations     18 June 2010 (USA)         1
                         The Hero: Love Story of a Spy  tt0347167  https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Herolovestoryofaspy.jpg/220px-Herolovestoryofaspy.jpg                        https://en.wikipedia.org/wiki/The_Hero:_Love_Story_of_a_Spy  The Hero: Love Story of a Spy  The Hero: Love Story of a Spy  0         2003             160      5.2          1901        Arun Khanna is a spy for the Indian government whose aid is enlisted to stop ISI Chief Ishak Khan. Khan is trying to build a nuclear bomb with which he can liberate Kashmir from the Indians. A battle of wits ensues. When Khan detonates a bomb at Khanna's engagement party to a fellow spy  Khanna's resolve is only strengthened. Now not only does he have to fight Khan  but he also has to track down his missing fiancee.                                                                                                                                                                                                                                                                                                                             Arun is an Indian undercover agent enlisted to stop ISI chief Ishaq Khan. The village girl Reshma helps him but endangers her own life.                                                                             Love story of a spy                                 Sunny Deol|Preity Zinta|Priyanka Chopra|Amrish Puri|Kabir Bedi|Parvin Dabas|Rajpal Yadav|Yvonne Maverick|                                                                                                             6 nominations             10 April 2003 (India)      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
Horror                   Alone (2015 Hindi film)        tt4271730  https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Alone_-_2015_Hindi_film_poster.jpg/220px-Alone_-_2015_Hindi_film_poster.jpg  https://en.wikipedia.org/wiki/Alone_(2015_Hindi_film)        Alone                          Alone                          0         2015             133      3.7          1465        Conjoined at birth  Anjana and Sanjana were twin sisters who lived by one promise made to each other - 'We will always be together. We will never separate'. Mysterious circumstances lead to the death of one while the other survived. Years later  the ghost of the dead comes back to haunt the surviving sister. Why was the promise broken?                                                                                                                                                                                                                                                                                                                                                                                                               A supernatural mystery about a young woman whose dead sister relentlessly haunts her.                                                                                                                               She was never alone                                 Bipasha Basu|Karan Singh Grover|Sulabha Arya|Zakir Hussain|Neena Gupta|Nilima Priya|Sanjay Sharma|                                                                                                                    1 win                     16 January 2015 (India)    1
                         Ragini MMS 2                   tt2609218  https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Ragini_MMS_2_Poster.jpg/220px-Ragini_MMS_2_Poster.jpg                        https://en.wikipedia.org/wiki/Ragini_MMS_2                   Ragini MMS 2                   Ragini MMS 2                   0         2014             119      3.8          2521        The film revolves around a haunted house where an infamous MMS is shot on a girl called Ragini which goes viral. the girl kills her boyfriend and claims that a witch had killed him. She ends up in a mental asylum. Later a film is planned based on the story  the same haunted house being the location of the film. Sunny Leone is cast to play the role or Ragini. Sunny goes to meet Ragini to understand her role better. But the meeting turns out violent. On one hand Ragini's doctor tries to solve the mystery and on the other hand shooting starts with unexplainable events. Junior artists get killed one by one. At last the scriptwriter Satya and Dr. Dutta have to fight the ghost to stay alive and save Sunny.                           A sleazy film director's decision to shoot his latest erotic horror movie in a notorious haunted house angers the vengeful spirit of its past inhabitant.                                                           Do Mein Zyada Maza Hai.                             Sunny Leone|Saahil Prem|Parvin Dabas|Sandhya Mridul|Divya Dutta|Soniya Mehra|Anita Hassanandani Reddy|Karan Veer Mehra|Karan Taluja|Kainaz Motivala|Rani Vashisht|Sagar Talashikar|Geetanjali Kulkarni|Jasvir Saini|  4 wins & 2 nominations    21 March 2014 (India)      1
Mystery|Thriller         Kahaani                        tt1821480  https://upload.wikimedia.org/wikipedia/en/thumb/8/85/KahaaniPoster.jpg/220px-KahaaniPoster.jpg                                    https://en.wikipedia.org/wiki/Kahaani                        Kahaani                        Kahaani                        0         2012             122      8.1          53181       Kolkata is abuzz with the preparations for the annual Durga Puja festival  as seven months pregnant Vidya Bagchi steps off the airplane from London. Her first stop is the local police station to file a missing person report. Weeks ago  her husband Arnab arrived in India for a job assignment. The first two weeks  they talked daily on the phone  and then without explanation  his calls stopped. Everywhere Vidya turns  no one can remember Arnab. There is no trace of him at the guest house or his workplace. But Vidya will not give up her search. Somewhere in Kolkata she will discover the dangerous truth.                                                                                                                                  A pregnant woman's search for her missing husband takes her from London to Kolkata  but everyone she questions denies having ever met him.                                                                          A mother of a story                                 Vidya Balan|Parambrata Chattopadhyay|Indraneil Sengupta|Nawazuddin Siddiqui|Dhritiman Chatterjee|Saswata Chatterjee|Darshan Jariwala|                                                                                 19 wins & 18 nominations  9 March 2012 (India)       1
                         Rahasya                        tt3337550  https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Rahasya_poster.jpg/220px-Rahasya_poster.jpg                                  https://en.wikipedia.org/wiki/Rahasya                        Rahasya                        Rahasya                        0         2015             123      7.6          3950        A Doctor stands accused of killing his own eighteen-year old daughter. While this aggrieved father protests his innocence  all evidence points towards him irrefutably. While his own wife suspects him too  the C.B.I. sleuth on the case concludes that the doctor could not have killed his own daughter. So then  who did it? And why? As the C.B.I sleuth seeks these answers  he uncovers a vicious web of adultery and hidden family secrets...                                                                                                                                                                                                                                                                                                          A Doctor stands accused of killing his own eighteen-year old daughter. While this aggrieved father protests his innocence  all evidence points towards him irrefutably. While his own wife ...                      Can a father kill his own daughter?                 Kay Kay Menon|Ashish Vidyarthi|Tisca Chopra|Mita Vasisht|Ashwini Kalsekar|Kakar Vinit|Jitendra Barsiwal|Farida Dadi|Ramesh Deo|Usha Jadhav|Bikramjeet Kanwarpal|Murari Kumar|Aarush Maurya|Nimai Bali|                1 win                     30 January 2015 (India)    1
Thriller                 Road (film)                    tt0315632  https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Road_poster.jpg/220px-Road_poster.jpg                                        https://en.wikipedia.org/wiki/Road_(2002_film)               Road                           Road                           0         2002             134      5.6          1099        Arvind Chauhan (Vivek Oberooi) and Lakhsmi (Antara Mali) are in love with each other. Lakhsmi's dad  a senior police inspector  hates Arvind  and so Arvind and Lakshmi decide to elope and get married. On the way they allow Babu  a stranded motorist  to ride with them. After a short while  Babu irritates both of them and they ask him to leave  instead Babu draws a gun  and asks Arvind to get out  and drives away with Lakhsmi. Arvind  with the help of a truck-driver  Inderpal (Makrand Deshpande)  catches up with Babu  and Babu runs away. Arvind files a police report  and they proceed on their way. That's when they find Babu in the back of their vehicle  angry and resentful  and this time determined to have his way with them...  A couple decide to pick up a hitchhiker  but he ends up being a psychotic stalker who puts in them in danger.                                                                                                       Drive carefully                                     Manoj Bajpayee|Vivek Oberoi|Antara Mali|Sayaji Shinde|Makrand Deshpande|Rajpal Yadav|Vijay Raaz|Ganesh Yadav|Raj Zutshi|Rajnish Thakur|Mithilesh Chaturvedi|Vidya Phadnis|Ganesh Acharya|                             1 win & 2 nominations     27 September 2002 (USA)    1
Name: count, Length: 298, dtype: int64

In [208]:
gen.first()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
genres,,,,,,,,,,,,,,,,,
Action,Dabangg 3,tt7059844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dabangg_3,Dabangg 3,Dabangg 3,0,2019,160,3.0,15000,Third installment of the Dabanng film series.,Third installment of the Dabanng film series.,File of Abhinay Chakra.,Salman Khan|Sonakshi Sinha|Sudeep|Mahesh Manjr...,1 win,16 March 2017 (India)
Action|Adventure,Junglee (2019 film),tt7463730,https://upload.wikimedia.org/wikipedia/en/e/e2...,https://en.wikipedia.org/wiki/Junglee_(2019_film),Junglee,Junglee,0,2019,115,5.3,1064,Dipankar Nair runs a Elephant sanctuary but th...,The story revolves around a vet who on his ho...,Betrayal. Friendship. Bravery.,Vidyut Jammwal|Lars Kjeldsen|,1 win,29 March 2019 (USA)
Action|Adventure|Animation,Arjun: The Warrior Prince,tt2404027,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Arjun:_The_Warri...,Arjun: The Warrior Prince,Arjun: The Warrior Prince,0,2012,96,6.8,1286,Legend knows him as an archer of unwavering fo...,The tale of how Arjuna fought his inner self a...,None,Yudhveer Bakoliya|Ashok Banthia|Ravi Khanvilka...,1 nomination,25 May 2012 (India)
Action|Adventure|Comedy,Total Dhamaal,tt7639372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Total_Dhamaal,Total Dhamaal,Total Dhamaal,0,2019,130,4.3,4817,Total Dhamaal is the third instalment in the D...,A group of people learn about a hidden treasur...,The Wildest Adventure Ever,Ajay Devgn|Madhuri Dixit|Anil Kapoor|Riteish D...,11 wins & 17 nominations,22 February 2019 (India)
Action|Adventure|Crime,Jai Veeru,tt1369669,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jai_Veeru,Jai Veeru: Friends Forever,Jai Veeru: Friends Forever,0,2009,160,3.5,237,Bangkok-based con-man Jai steals cars and c...,Best friends Jai and Veeru teams up together t...,None,Fardeen Khan|Kunal Khemu|Dia Mirza|Anjana Sukh...,None,11 March 2009 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Romance|Thriller,Valentine's Night,tt2211133,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Valentine%27s_Night,Valentine's Night,Valentine's Night,0,2012,\N,2.7,23,A guy falls in love blindly with a beautiful g...,Add a Plot »,None,Shikhi Gupta|Sunny Hinduja|Prabhat Kumar|Rahul...,8 nominations,14 December 2012 (India)
Sci-Fi,Aalaap (film),tt2243336,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aalaap_(film),Aalaap,Aalaap,0,2012,116,5.8,23,Artdirector Md asdulla khan,Artdirector Md asdulla khan,None,Omkar Das Manikpuri|Pitobash|Amit Purohit|Vija...,None,27 July 2012 (India)
Sport,22 Yards,tt9496212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/22_Yards,22 Yards,22 Yards,0,2019,126,5.3,124,A dramatic portrayal of a victorious tale of a...,A dramatic portrayal of a victorious tale of a...,None,Barun Sobti|Rajit Kapur|Panchhi Bora|Kartikey ...,None,15 March 2019 (India)
Thriller,Risknamaa,tt9795264,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Risknamaa,Risknamaa,Risknamaa,0,2019,123,6.7,11,Sher Singh is the Sarpanch of his village. Who...,Sher Singh is the Sarpanch of his village. Who...,The Clan with a Plan,Garima Agarwal|Anupama|Parveen Bansala|Mahavee...,1 nomination,15 March 2019 (India)
War,Battalion 609,tt9472208,None,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,None,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,None,11 January 2019 (India)

In [209]:
gen.last()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
genres,,,,,,,,,,,,,,,,,
Action,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,The power of students,Gippy Grewal|Zareen Khan|,1 nomination,1 November 2019 (USA)
Action|Adventure,Zokkomon,tt1605790,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zokkomon,Zokkomon,Zokkomon,0,2011,109,4.0,274,After the passing of his parents in an acciden...,An orphan is abused and abandoned believed to...,Betrayal. Friendship. Bravery.,Darsheel Safary|Anupam Kher|Manjari Fadnnis|Ti...,1 win,22 April 2011 (India)
Action|Adventure|Animation,Toonpur Ka Super Hero,tt1189006,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Toonpur_Ka_Super...,Toonpur Ka Superrhero,Toonpur Ka Superrhero,0,2010,95,4.2,628,There is trouble brewing in the land of cartoo...,A reel-life costumed actor is abducted and ask...,None,Ajay Devgn|Kajol|Ameya Pandya|Chinky Jaiswal|T...,2 wins,24 December 2010 (India)
Action|Adventure|Comedy,Bombay to Goa (2007 film),tt1083988,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombay_to_Goa_(2...,Journey Bombay to Goa: Laughter Unlimited,Journey Bombay to Goa: Laughter Unlimited,0,2007,138,4.5,309,Lal wants to start his tourist bus service and...,After learning a secret of a treasure from a r...,Laughter unlimited,Sunil Pal|Raju Srivastava|Vijay Raaz|Ehsaan Qu...,1 nomination,6 July 2007 (India)
Action|Adventure|Crime,Jai Veeru,tt1369669,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jai_Veeru,Jai Veeru: Friends Forever,Jai Veeru: Friends Forever,0,2009,160,3.5,237,Bangkok-based con-man Jai steals cars and c...,Best friends Jai and Veeru teams up together t...,None,Fardeen Khan|Kunal Khemu|Dia Mirza|Anjana Sukh...,None,11 March 2009 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Romance|Thriller,Pyaar Tune Kya Kiya,tt0281102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pyaar_Tune_Kya_Kiya,Pyaar Tune Kya Kiya...,Pyaar Tune Kya Kiya...,0,2001,123,5.7,719,Ria Jaiswal lives a very wealthy lifestyle alo...,A obsessive woman determines to do what it tak...,None,Fardeen Khan|,8 nominations,27 April 2001 (India)
Sci-Fi,Aalaap (film),tt2243336,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aalaap_(film),Aalaap,Aalaap,0,2012,116,5.8,23,Artdirector Md asdulla khan,Artdirector Md asdulla khan,None,Omkar Das Manikpuri|Pitobash|Amit Purohit|Vija...,None,27 July 2012 (India)
Sport,22 Yards,tt9496212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/22_Yards,22 Yards,22 Yards,0,2019,126,5.3,124,A dramatic portrayal of a victorious tale of a...,A dramatic portrayal of a victorious tale of a...,None,Barun Sobti|Rajit Kapur|Panchhi Bora|Kartikey ...,None,15 March 2019 (India)
Thriller,Road (film),tt0315632,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Road_(2002_film),Road,Road,0,2002,134,5.6,1099,Arvind Chauhan (Vivek Oberooi) and Lakhsmi (An...,A couple decide to pick up a hitchhiker but h...,Drive carefully,Manoj Bajpayee|Vivek Oberoi|Antara Mali|Sayaji...,1 win & 2 nominations,27 September 2002 (USA)
War,Battalion 609,tt9472208,None,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,None,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,None,11 January 2019 (India)

In [210]:
gen.nth(4)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
20,Mere Pyare Prime Minister,tt8207768,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Pyare_Prime...,Mere Pyare Prime Minister,Mere Pyare Prime Minister,0,2018,104,Drama,6.8,344,A story about four children living in a Mumbai...,A story about four children living in a Mumbai...,Meri Ek Arzi Sun Lo Zara,Rasika Agashe|Sonia Albizuri|Syna Anand|Adarsh...,NaN,15 March 2019 (India)
62,Saand Ki Aankh,tt8108206,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Saand_Ki_Aankh,Saand Ki Aankh,Saand Ki Aankh,0,2019,146,Biography|Drama,8.9,1902,Both over the age of 60 Chandro Tomar and Pra...,Both over the age of 60 Chandro Tomar and Pra...,NaN,Taapsee Pannu|Bhumi Pednekar|Prakash Jha|Viine...,1 nomination,25 October 2019 (USA)
74,Dil Bechara,tt8110330,NaN,https://en.wikipedia.org/wiki/Dil_Bechara,Dil Bechara,Dil Bechara,0,2019,101,Drama|Romance,6.6,117000,A love story about two cancer patients.,A love story about two cancer patients.,NaN,Sushant Singh Rajput|Sanjana Sanghi|Sahil Vaid|,NaN,NaN
75,Pati Patni Aur Woh (2019 film),tt9680136,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pati_Patni_Aur_W...,Pati Patni Aur Woh,Pati Patni Aur Woh,0,2019,126,Comedy|Romance,5.7,6100,Chintu Tyagi is an ordinary middle class man ...,Chintu Tyagi is an ordinary middle class man ...,NaN,Kartik Aaryan|Bhumi Pednekar|Ananya Panday|Apa...,NaN,NaN
87,Aiyaary,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...,1 nomination,16 February 2018 (USA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,Om (2003 film),tt0358613,NaN,https://en.wikipedia.org/wiki/Om_(2003_film),Om,Om,0,2003,\N,Action|Romance,4.0,29,Om lives in Bombay India in a small apartmen...,Om lives in Bombay India in a small apartmen...,NaN,Attin Bhalla|Sandali Sinha|Smita Jaykar|Pankaj...,NaN,21 March 2003 (India)
1505,Mujhse Dosti Karoge!,tt0272736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mujhse_Dosti_Kar...,Mujhse Dosti Karoge!,Mujhse Dosti Karoge!,0,2002,149,Drama|Family|Musical,5.0,4604,Pooja Sahani Tina Kapoor and Raj Khanna are c...,A young man in England regularly mails his chi...,NaN,Hrithik Roshan|Kareena Kapoor|Rani Mukerji|Uda...,1 nomination,9 August 2002 (India)
1546,Om Jai Jagadish,tt0327071,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Om_Jai_Jagadish,Om Jai Jagadish,Om Jai Jagadish,0,2002,172,Drama|Musical,5.5,1713,Widowed Mrs. Saraswati Batra (Waheeda Rehman) ...,Widowed Mrs. Saraswati Batra (Waheeda Rehman) ...,A prayer for togetherness,Waheeda Rehman|Anil Kapoor|Fardeen Khan|Abhish...,NaN,8 July 2002 (India)
1581,Aśoka (film),tt0249371,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/A%C5%9Boka_(film),Ashoka the Great,Asoka,0,2001,176,Action|Biography|Drama,6.5,12612,Prince Ashoke (Shahrukh Khan) heir to the Mag...,The epic tale of King Asoka's life is recounte...,Only the dead have seen the end of war.,Shah Rukh Khan|Kareena Kapoor|Danny Denzongpa|...,2 wins & 17 nominations,26 October 2001 (India)
1616,Rehnaa Hai Terre Dil Mein,tt0299108,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rehnaa_Hai_Terre...,Rehnaa Hai Terre Dil Mein,Rehnaa Hai Terre Dil Mein,0,2001,160,Musical|Romance,7.5,6232,Madhav (Maddy) has love at first site with Ree...,A young girl is torn between an obsessive love...,NaN,Madhavan|Saif Ali Khan|Dia Mirza|Vrajesh Hirje...,2 wins & 4 nominations,19 October 2001 (India)

In [211]:
gen.get_group('Thriller')

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
19,Risknamaa,tt9795264,NaN,https://en.wikipedia.org/wiki/Risknamaa,Risknamaa,Risknamaa,0,2019,123,Thriller,6.7,11,Sher Singh is the Sarpanch of his village. Who...,Sher Singh is the Sarpanch of his village. Who...,NaN,Garima Agarwal|Anupama|Parveen Bansala|Mahavee...,NaN,15 March 2019 (India)
29,Setters (film),tt9239772,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Setters_(film),Setters,Setters,0,2019,126,Thriller,5.1,158,A thriller set in Benares Jaipur Mumbai and ...,A thriller set in Benares Jaipur Mumbai and ...,NaN,Shreyas Talpade|Aftab Shivdasani|Sonnalli Seyg...,NaN,3 May 2019 (India)
73,Yeh Saali Aashiqui,tt10443846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Saali_Aashiqui,Yeh Saali Aashiqui,Yeh Saali Aashiqui,0,2019,137,Thriller,7.9,3200,NaN,Add a Plot »,NaN,Vardhan Puri|Jessey Lever|,NaN,NaN
82,My Birthday Song,tt4335954,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/My_Birthday_Song,My Birthday Song,My Birthday Song,0,2018,95,Thriller,5.5,215,After a wild night of impulse and passion adv...,After a wild night of impulse and passion adv...,NaN,Nora Fatehi|Elena Kazan|Suparna Krishna|Pitoba...,NaN,19 January 2018 (India)
149,Kaashi in Search of Ganga,tt7274806,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kaashi_in_Search...,Kaashi in Search of Ganga,Kaashi in Search of Ganga,0,2018,125,Thriller,5.6,201,The movie is about two siblings Kashi (Sharma...,The movie is about two siblings Kashi (Sharma...,NaN,Aishwarya Devan|Kranti Prakash Jha|Manoj Joshi...,NaN,26 October 2018 (India)
187,Maatr,tt5543746,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Maatr,Maatr,Maatr,0,2017,113,Thriller,4.5,321,Vidya who's left shattered after her daughter...,Vidya who's left shattered after her daughter...,NaN,Raveena Tandon|Madhur Mittal|Siddharth Bhardwa...,NaN,21 April 2017 (India)
235,Ranchi Diaries,tt7154994,https://upload.wikimedia.org/wikipedia/commons...,https://en.wikipedia.org/wiki/Ranchi_Diaries,Ranchi Diaries,Ranchi Diaries,0,2017,93,Thriller,7.4,69,Ranchi Diaries depicts the story of Gudiya and...,An aspiring model her friends and her godfath...,The Clan with a Plan,Soundarya Sharma|Pradeep Singh|Anupam Kher|Jim...,NaN,13 October 2017 (India)
277,Love Games (film),tt5518128,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Love_Games_(film),Love Games,Love Games,0,2016,114,Thriller,4.3,744,A pair of nymphomaniacs compete in seducing co...,A pair of nymphomaniacs compete in seducing co...,NaN,Patralekhaa Paul|Tara-Alisha Berry|Gaurav Aror...,1 nomination,8 April 2016 (India)
282,Global Baba,tt3590416,NaN,https://en.wikipedia.org/wiki/Global_Baba,Global Baba,Global Baba,0,2016,120,Thriller,5.6,163,A conman finds refuge in becoming a baba and c...,A conman finds refuge in becoming a baba and c...,Satta Aur Satsang,Pankaj Tripathi|Sandeepa Dhar|Ravi Kishan|Abhi...,NaN,11 March 2016 (India)
473,Karar: The Deal,tt3565354,NaN,https://en.wikipedia.org/wiki/Karar:_The_Deal,Karar: The Deal,Karar: The Deal,0,2014,115,Thriller,4.3,53,Nikita the granddaughter of a rich and old ma...,Nikita the granddaughter of a rich and old ma...,Mera jism... Mera hatyaar (My body... My weapon),Mahek Chahal|Tarun Arora|Shashi Wadia|,NaN,21 February 2014 (India)
497,The Xposé,tt3645014,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Xpos%C3%A9,The Xpose,The Xpose,0,2014,113,Thriller,3.2,1419,This is a dramatic chain of events in the most...,This is a dramatic chain of events in the most...,NaN,Himesh Reshammiya|Yo Yo Honey Singh|Irrfan Kha...,1 win & 2 nominations,16 May 2014 (India)
568,Dehraadun Diary,tt2613942,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dehraadun_Diary,Dehraadun Diary,Dehraadun Diary,0,2013,\N,Thriller,5.9,44,The story revolves around the daughter of a po...,The story revolves around the daughter of a po...,NaN,Adhyayan Suman|Rati Agnihotri|,NaN,NaN
642,Maazii,tt2554042,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Maazii_(2013_film),Maazii,Maazii,0,2013,123,Thriller,6.7,64,Tarun and his wife Shrishti are living a happy...,Tarun and his wife Shrishti are living a happy...,NaN,Sumit Nijhawan|Mona Wasu|,1 win,27 September 2013 (India)
675,Married 2 America,tt2158633,NaN,https://en.wikipedia.org/wiki/Married_2_America,Married 2 America,Married 2 America,0,2012,\N,Thriller,4.3,14,Ravi Malhotra an NRI living in the US works ...,Anjali Malhotra comes to India in search of he...,NaN,Archana Joglekar|Akhilendra Mishra|Chetan Pand...,NaN,NaN
692,Rakhtbeej,tt3431756,NaN,https://en.wikipedia.org/wiki/Rakhtbeej,Rakhtbeej,Rakhtbeej,0,2012,120,Thriller,3.1,9,Rakhtbeej is the story of two men from two di...,Rakhtbeej is the story of two men from two di...,NaN,Julia Datt|,NaN,25 May 2012 (India)
699,Paanch Ghantey Mien Paanch Crore,tt1563732,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paanch_Ghantey_M...,5 Ghantey Mien 5 Crore,5 Ghantey Mien 5 Crore,0,2012,111,Thriller,5.2,59,The film tells the story of chartered accounta...,The film tells the story of chartered accounta...,Murder.. Sex.. Money.. Betrayal.. Everything T...,Nassar Abdulla|Shawar Ali|Rashid Khan|Sameer K...,NaN,10 August 2012 (India)
1064,Chhodon Naa Yaar,tt1108831,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chhodon_Naa_Yaar,Chhodon Naa Yaar,Chhodon Naa Yaar,0,2007,\N,Thriller,4.7,84,Three college friends decide to make the film ...,Three college friends decide to make the film ...,NaN,Jimmy Sheirgill|Kim Sharma|Farid Amiri|Kabir S...,NaN,NaN
1201,Souten: The Other Woman,tt0833537,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Souten:_The_Othe...,Souten: The Other Woman,Souten: The Other Woman,0,2006,\N,Thriller,4.8,34,After the accidental death of her lover Mital...,After the accidental death of her lover Mital...,NaN,Mahima Chaudhry|Padmini Kolhapure|Shakti Kapoo...,NaN,24 March 2006 (India)
1232,Chetna: The Excitement,tt0487149,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chetna:_The_Exci...,Chetna: The Excitement,Chetna: The Excitement,0,2005,102,Thriller,3.2,39,NaN,Add a Plot »,NaN,Jatin Grewal|Kiran Kumar|Navnit Ravi Rana|,NaN,24 June 2005 (India)
1238,Chehraa,tt0449870,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chehraa_(2005_film),Chehraa,Chehraa,0,2005,136,Thriller,3.8,112,Reena and fellow collegian Akash Mehta are med...,Reena and fellow collegian Akash Mehta are med...,NaN,Bipasha Basu|Dino Morea|Preeti Jhangiani|Irrfa...,NaN,18 February 2005 (India)
1246,Fun – Can Be Dangerous Sometimes,tt0497620,NaN,https://en.wikipedia.org/wiki/Fun_%E2%80%93_Ca...,Fun: Can Be Dangerous Sometimes,Fun: Can Be Dangerous Sometimes,0,2005,138,Thriller,3.3,66,The film begins as a raunchy Bollywood sex far...,A trio of thrill-seeking housewives plot to i...,NaN,Siddharth Koirala|Aryan Vaid|Payal Rohatgi|Hin...,NaN,25 February 2005 (India)
1431,Ek Din 24 Ghante,tt0380337,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Din_24_Ghante,Ek Din 24 Ghante,Ek Din 24 Ghante,0,2003,95,Thriller,4.0,75,Sameera Dutta is an enlightened and intelligen...,Sameera Dutta is an enlightened and intelligen...,NaN,Rahul Bose|Ahmed Chaudhary|Nandita Das|Vineet ...,NaN,7 November 2003 (India)
1551,Road (film),tt0315632,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Road_(2002_film),Road,Road,0,2002,134,Thriller,5.6,1099,Arvind Chauhan (Vivek Oberooi) and Lakhsmi (An...,A couple decide to pick up a hitchhiker but h...,Drive carefully,Manoj Bajpayee|Vivek Oberoi|Antara Mali|Sayaji...,1 win & 2 nominations,27 September 2002 (USA)

In [212]:
gen.groups

{'Action': [78, 176, 367, 368, 435, 452, 535, 538, 637, 1146, 1171, 1310, 1411, 1585, 1627], 'Action|Adventure': [24, 166, 756], 'Action|Adventure|Animation': [685, 706, 903], 'Action|Adventure|Comedy': [13, 203, 314, 321, 537, 598, 789, 1029, 1044, 1067, 1070], 'Action|Adventure|Crime': [928], 'Action|Adventure|Drama': [34, 198, 318, 355, 821, 858, 905, 944, 1009, 1011, 1302, 1330, 1398], 'Action|Adventure|Fantasy': [965, 1026, 1190], 'Action|Adventure|Sci-Fi': [552, 807], 'Action|Adventure|Thriller': [159, 671, 962, 1488], 'Action|Biography|Crime': [105, 220, 294, 668], 'Action|Biography|Drama': [8, 354, 526, 1554, 1581], 'Action|Comedy': [16, 46, 71, 126, 161, 167, 223, 366, 522, 531, 593, 611, 629, 633, 729, 731, 734, 878, 975, 1256], 'Action|Comedy|Crime': [364, 505, 693, 694, 738, 775, 781, 816, 897, 920, 923, 937, 980, 1089, 1108, 1192, 1204, 1436, 1496, 1508, 1608], 'Action|Comedy|Drama': [47, 132, 155, 158, 362, 387, 390, 737, 790, 951, 959, 1111, 1168, 1236, 1253, 1314, 1320, 1381, 1408, 1468, 1523, 1602], 'Action|Comedy|Family': [1446], 'Action|Comedy|Fantasy': [61, 160], 'Action|Comedy|Music': [547], 'Action|Comedy|Musical': [733, 1383], 'Action|Comedy|Mystery': [990], 'Action|Comedy|Romance': [266, 361, 486, 595, 791, 919, 1368, 1509], 'Action|Comedy|Thriller': [201], 'Action|Comedy|War': [409], 'Action|Crime': [1124, 1170, 1418, 1586], 'Action|Crime|Drama': [14, 48, 96, 117, 165, 188, 251, 280, 297, 380, 391, 406, 442, 510, 524, 536, 587, 615, 624, 640, 651, 680, 698, 741, 754, 767, 769, 786, 800, 810, 814, 822, 853, 870, 877, 888, 891, 893, 927, 947, 953, 969, 977, 997, 1010, 1054, 1058, 1085, 1116, 1132, 1145, 1165, 1167, 1188, 1200, 1218, 1242, 1245, 1255, 1259, 1293, 1294, 1318, 1326, 1327, 1340, 1341, 1345, 1354, 1366, 1374, 1426, 1429, 1432, 1452, 1491, 1495, 1503, 1520, 1527, 1539, 1541, 1570, 1579, 1606, 1617], 'Action|Crime|Horror': [1578], 'Action|Crime|Mystery': [958], 'Action|Crime|Romance': [608], 'Action|Crime|Sci-Fi': [399, 1175], 'Action|Crime|Thriller': [38, 215, 384, 575, 580, 683, 732, 774, 832, 886, 1018, 1062, 1129, 1162, 1164, 1207, 1317, 1373, 1603], 'Action|Drama': [41, 56, 66, 112, 228, 263, 458, 468, 493, 523, 590, 659, 661, 751, 783, 1237, 1356, 1391, 1511, 1531, 1536, 1545, 1552, 1562, 1598], 'Action|Drama|Fantasy': [1139], 'Action|Drama|History': [22, 110, 128, 171, 184, 219, 359, 363, 982], 'Action|Drama|Horror': [776, 899], 'Action|Drama|Music': [210, 222, 327], 'Action|Drama|Musical': [356, 434, 1028, 1324, 1453], 'Action|Drama|Mystery': [379, 806, 839, 979, 1224, 1424, 1482], 'Action|Drama|Romance': [39, 55, 295, 342, 371, 457, 556, 628, 682, 861, 873, 995, 1050, 1071, 1121, 1357, 1361, 1394, 1404, 1443, 1455, 1466, 1480, 1502, 1532, 1569, 1577], 'Action|Drama|Sport': [84, 258, 307, 429, 850, 1154], 'Action|Drama|Thriller': [42, 77, 106, 164, 175, 278, 341, 433, 449, 600, 625, 672, 719, 743, 834, 866, 880, 884, 936, 1079, 1229, 1322, 1332, 1607], 'Action|Drama|War': [0, 716, 1039, 1325], 'Action|Fantasy|Sci-Fi': [1379], 'Action|Fantasy|Thriller': [441, 1385, 1525], 'Action|Horror|Sci-Fi': [527], 'Action|Musical|Romance': [1497], 'Action|Mystery|Romance': [179, 1555], 'Action|Mystery|Thriller': [393], 'Action|Romance': [68, 454, 502, 1262, 1462, 1537, 1558, 1560, 1590], 'Action|Romance|Thriller': [700, 1501], 'Action|Sci-Fi': [1186], 'Action|Sci-Fi|Thriller': [857, 934], 'Action|Thriller': [33, 51, 70, 76, 87, 99, 114, 123, 125, 150, 182, 276, 281, 284, 298, 305, 320, 346, 365, 476, 518, 561, 589, 596, 622, 652, 799, 915, 1032, 1243, 1257, 1331, 1351, 1498, 1575, 1593], 'Action|Thriller|War': [169], 'Adventure|Animation|Comedy': [1030], 'Adventure|Animation|Family': [887], 'Adventure|Biography|Drama': [431], 'Adventure|Comedy': [335], 'Adventure|Comedy|Crime': [712, 1074], 'Adventure|Comedy|Drama': [312, 428, 528, 648, 1184], 'Adventure|Drama|Family': [451], 'Adventure|Drama|Musical': [1567, 1568], 'Adventure|Drama|Mystery': [283], 'Adventure|Drama|Thriller': [286, 313, 1430], 'Adventure|Fantasy|Sci-Fi': [333], 'Adventure|Horror|Mystery': [1258, 1423], 'Adventure|Horror|Romance': [840], 'Adventure|Musical|Romance': [1382], 'Adventure|Thriller': [650], 'Animation': [605, 963, 1261], 'Animation|Comedy|Drama': [718], 'Animation|Drama|History': [1228], 'Animation|Drama|Musical': [724], 'Animation|Family|Musical': [574], 'Biography': [336], 'Biography|Crime|Drama': [638, 815], 'Biography|Crime|Thriller': [229], 'Biography|Drama': [2, 9, 31, 40, 62, 116, 135, 254, 270, 293, 374, 430, 494, 496, 817, 1083], 'Biography|Drama|History': [216, 224, 377, 895, 1076, 1275, 1370, 1499, 1550, 1623], 'Biography|Drama|Music': [360], 'Biography|Drama|Romance': [550, 1142, 1211], 'Biography|Drama|Sport': [288, 332, 612], 'Biography|Drama|Thriller': [269, 760], 'Biography|History': [186], 'Comedy': [43, 59, 64, 108, 109, 124, 138, 142, 163, 180, 189, 199, 213, 225, 232, 250, 259, 260, 273, 308, 317, 328, 338, 381, 402, 403, 411, 422, 424, 443, 445, 450, 487, 495, 504, 512, 540, 549, 551, 554, 559, 594, 643, 673, 686, 690, 697, 701, 705, 750, 842, 854, 860, 1056, 1061, 1094, 1182, 1219, 1227, 1248, 1277, 1283, 1307, 1352, 1375, 1380, 1392, 1439, 1441, 1471, 1475, 1486, 1557], 'Comedy|Crime': [438, 656, 901, 970, 981, 991, 1191], 'Comedy|Crime|Drama': [7, 113, 120, 285, 544, 772, 773, 794, 820, 862, 867, 882, 894, 932, 935, 942, 949, 964, 992, 1015, 1036, 1072, 1160, 1180, 1225, 1489, 1493], 'Comedy|Crime|Family': [413, 1604], 'Comedy|Crime|Mystery': [1073, 1364], 'Comedy|Crime|Romance': [988, 1610], 'Comedy|Crime|Thriller': [533, 609, 1247], 'Comedy|Drama': [6, 63, 72, 97, 121, 139, 147, 153, 183, 185, 193, 211, 236, 246, 249, 290, 337, 340, 401, 404, 405, 410, 414, 417, 419, 427, 469, 477, 481, 509, 546, 553, 569, 583, 586, 599, 602, 653, 711, 744, 748, 752, 753, 757, 762, 771, 778, 795, 813, 828, 838, 843, 845, 868, 872, 874, 885, 912, 916, 921, 924, 940, 943, 946, 950, 971, 972, 973, 999, 1012, 1023, 1024, 1034, 1037, 1043, 1051, 1077, 1082, 1095, 1104, 1195, 1220, 1348, 1386, 1459, 1479, 1622, 1626], 'Comedy|Drama|Family': [107, 156, 234, 425, 548, 688, 735, 759, 766, 777, 780, 939, 984, 1006, 1025, 1059, 1114, 1298, 1305, 1309, 1528, 1553, 1576, 1599], 'Comedy|Drama|Fantasy': [178, 309, 439, 485, 567, 714, 841, 844, 856, 900, 1013, 1174], 'Comedy|Drama|Horror': [103, 883], 'Comedy|Drama|Music': [819, 978], 'Comedy|Drama|Musical': [603, 908, 1101, 1119, 1282, 1290, 1316, 1400, 1403, 1415, 1507, 1544], 'Comedy|Drama|Mystery': [372], 'Comedy|Drama|Romance': [54, 79, 115, 145, 148, 157, 174, 191, 194, 209, 275, 322, 348, 357, 358, 385, 408, 437, 446, 448, 453, 463, 464, 470, 471, 483, 513, 539, 585, 604, 630, 647, 658, 662, 666, 689, 695, 709, 720, 736, 740, 742, 747, 770, 801, 804, 809, 811, 812, 824, 889, 892, 898, 902, 906, 907, 914, 931, 945, 957, 960, 961, 976, 983, 1001, 1003, 1008, 1035, 1038, 1040, 1075, 1084, 1087, 1092, 1093, 1097, 1102, 1106, 1107, 1112, 1155, 1183, 1187, 1189, 1196, 1230, 1264, 1272, 1274, 1291, 1319, 1359, 1376, 1395, 1437, 1438, 1463, 1529, 1542, 1563, ...], 'Comedy|Drama|Short': [1478], 'Comedy|Drama|Sport': [802, 956, 1476], 'Comedy|Drama|Thriller': [44, 511, 617, 620, 1017, 1133, 1206], ...}

In [213]:
gen.describe()

                           is_adult                                     \
                              count mean  std  min  25%  50%  75%  max
genres
Action                         15.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Action|Adventure                3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Animation      3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Comedy        11.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Action|Adventure|Crime          1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
...                             ...  ...  ...  ...  ...  ...  ...  ...
Romance|Thriller                4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Sci-Fi                          1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Sport                           1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
Thriller                       23.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
War                             1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0

                           year_of_release               ... imdb_rating       \
                                     count         mean  ...         75%  max
genres                                                   ...
Action                                15.0  2011.866667  ...        6.00  7.4
Action|Adventure                       3.0  2016.000000  ...        4.65  5.3
Action|Adventure|Animation             3.0  2011.333333  ...        6.55  6.8
Action|Adventure|Comedy               11.0  2012.272727  ...        6.00  7.2
Action|Adventure|Crime                 1.0  2009.000000  ...        3.50  3.5
...                                    ...          ...  ...         ...  ...
Romance|Thriller                       4.0  2008.000000  ...        4.80  5.7
Sci-Fi                                 1.0  2012.000000  ...        5.80  5.8
Sport                                  1.0  2019.000000  ...        5.30  5.3
Thriller                              23.0  2012.260870  ...        5.60  7.9
War                                    1.0  2019.000000  ...        4.10  4.1

                           imdb_votes                                   \
                                count         mean          std    min
genres
Action                           15.0  4546.466667  8137.841455    5.0
Action|Adventure                  3.0  5772.666667  8848.630704  274.0
Action|Adventure|Animation        3.0   690.333333   567.075245  157.0
Action|Adventure|Comedy          11.0  6717.818182  5899.471702  309.0
Action|Adventure|Crime            1.0   237.000000          NaN  237.0
...                               ...          ...          ...    ...
Romance|Thriller                  4.0   255.500000   328.578250   21.0
Sci-Fi                            1.0    23.000000          NaN   23.0
Sport                             1.0   124.000000          NaN  124.0
Thriller                         23.0   358.826087   718.092337    9.0
War                               1.0    73.000000          NaN   73.0


                               25%     50%     75%      max
genres
Action                        11.0    38.0  4989.0  21430.0
Action|Adventure             669.0  1064.0  8522.0  15980.0
Action|Adventure|Animation   392.5   628.0   957.0   1286.0
Action|Adventure|Comedy     2530.5  5976.0  9383.5  20431.0
Action|Adventure|Crime       237.0   237.0   237.0    237.0
...                            ...     ...     ...      ...
Romance|Thriller              22.5   141.0   374.0    719.0
Sci-Fi                        23.0    23.0    23.0     23.0
Sport                        124.0   124.0   124.0    124.0
Thriller                      48.5    75.0   208.0   3200.0
War                           73.0    73.0    73.0     73.0

[205 rows x 32 columns]

In [214]:
# gen.sample(1,replace=True)

In [215]:
movie.head(0)

Empty DataFrame
Columns: [title_x, imdb_id, poster_path, wiki_link, title_y, original_title, is_adult, year_of_release, runtime, genres, imdb_rating, imdb_votes, story, summary, tagline, actors, wins_nominations, release_date]
Index: []

In [216]:

gen.agg(
    {
    'runtime' :'max',
    'imdb_rating':'min',
    'imdb_votes':'mean'
    }
)

                           runtime  imdb_rating   imdb_votes
genres
Action                          \N          2.9  4546.466667
Action|Adventure               164          4.0  5772.666667
Action|Adventure|Animation      96          4.2   690.333333
Action|Adventure|Comedy        171          1.7  6717.818182
Action|Adventure|Crime         160          3.5   237.000000
...                            ...          ...          ...
Romance|Thriller                \N          2.7   255.500000
Sci-Fi                         116          5.8    23.000000
Sport                          126          5.3   124.000000
Thriller                        \N          3.1   358.826087
War                            131          4.1    73.000000

[205 rows x 3 columns]

In [217]:
ipl.head(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [218]:
pom = ipl.groupby('City')

In [219]:
pom.agg(
    {
    'Margin':'mean'
    # 'WinningTeam':'sum'
    
    }
)

                   Margin
City
Abu Dhabi       17.971429
Ahmedabad       15.888889
Bangalore       23.870968
Bengaluru        8.571429
Bloemfontein    10.000000
Cape Town       27.166667
Centurion       10.833333
Chandigarh      14.803571
Chennai         17.169231
Cuttack         13.285714
Delhi           17.631579
Dharamsala      33.555556
Dubai           12.000000
Durban          12.800000
East London     31.333333
Hyderabad       15.507937
Indore           9.888889
Jaipur          15.787234
Johannesburg     7.500000
Kanpur           5.500000
Kimberley       21.000000
Kochi           24.600000
Kolkata         14.772152
Mumbai          15.265823
Nagpur           7.000000
Navi Mumbai     21.555556
Port Elizabeth  31.714286
Pune            21.862745
Raipur           7.666667
Rajkot          13.111111
Ranchi           9.285714
Sharjah         13.100000
Visakhapatnam   24.000000

In [220]:
mar = ipl.groupby('Date')

In [221]:
# ipl.groupby('MatchNumber').agg(['min' ,'max'])

In [222]:
ipl.groupby('MatchNumber').agg({'Margin': ['min', 'max']})

            Margin
               min    max
MatchNumber
1              1.0  140.0
10             4.0   66.0
11             2.0  118.0
12             4.0   45.0
13             4.0   71.0
...            ...    ...
Final          1.0   58.0
Qualifier      2.0   14.0
Qualifier 1    4.0   57.0
Qualifier 2    3.0   86.0
Semi Final     6.0  105.0

[80 rows x 2 columns]

In [223]:
gen

In [224]:
for group,data in gen:
    # print(type(group))
    df=data[data['imdb_rating']==data['imdb_rating'].max()]
df

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [225]:
# movies starts with A
def foo(group):
    # print(group)
    return group

In [226]:
gen.apply(foo)

C:\Users\MRINMAY\AppData\Local\Temp\ipykernel_6780\1102184947.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  gen.apply(foo)

                                        title_x    imdb_id  \
genres
Action   78                           Dabangg 3  tt7059844
         176                       Aa Gaya Hero  tt5896934
         367                     Gabbar Is Back  tt2424988
         368                     Gabbar Is Back  tt2424988
         435                        Sorry Daddy  tt4994210
...                                         ...        ...
Thriller 1238                           Chehraa  tt0449870
         1246  Fun – Can Be Dangerous Sometimes  tt0497620
         1431                  Ek Din 24 Ghante  tt0380337
         1551                       Road (film)  tt0315632
War      1                        Battalion 609  tt9472208

                                                     poster_path  \
genres
Action   78    https://upload.wikimedia.org/wikipedia/en/thum...
         176   https://upload.wikimedia.org/wikipedia/en/thum...
         367   https://upload.wikimedia.org/wikipedia/en/thum...
         368   https://upload.wikimedia.org/wikipedia/en/thum...
         435   https://upload.wikimedia.org/wikipedia/en/thum...
...                                                          ...
Thriller 1238  https://upload.wikimedia.org/wikipedia/en/thum...
         1246                                                NaN
         1431  https://upload.wikimedia.org/wikipedia/en/thum...
         1551  https://upload.wikimedia.org/wikipedia/en/thum...
War      1                                                   NaN

                                                       wiki_link  \
genres
Action   78              https://en.wikipedia.org/wiki/Dabangg_3
         176          https://en.wikipedia.org/wiki/Aa_Gaya_Hero
         367        https://en.wikipedia.org/wiki/Gabbar_Is_Back
         368        https://en.wikipedia.org/wiki/Gabbar_is_Back
         435    https://en.wikipedia.org/wiki/Sorry_Daddy_(film)
...                                                          ...
Thriller 1238  https://en.wikipedia.org/wiki/Chehraa_(2005_film)
         1246  https://en.wikipedia.org/wiki/Fun_%E2%80%93_Ca...
         1431     https://en.wikipedia.org/wiki/Ek_Din_24_Ghante
         1551     https://en.wikipedia.org/wiki/Road_(2002_film)
War      1           https://en.wikipedia.org/wiki/Battalion_609

                                       title_y  \
genres
Action   78                          Dabangg 3
         176                      Aa Gaya Hero
         367                    Gabbar is Back
         368                    Gabbar is Back
         435                       Sorry Daddy
...                                        ...
Thriller 1238                          Chehraa
         1246  Fun: Can Be Dangerous Sometimes
         1431                 Ek Din 24 Ghante
         1551                             Road
War      1                       Battalion 609

                                original_title  is_adult  year_of_release  \
genres
Action   78                          Dabangg 3         0             2019
         176                      Aa Gaya Hero         0             2017
         367                    Gabbar is Back         0             2015
         368                    Gabbar is Back         0             2015
         435                       Sorry Daddy         0             2015
...                                        ...       ...              ...
Thriller 1238                          Chehraa         0             2005
         1246  Fun: Can Be Dangerous Sometimes         0             2005
         1431                 Ek Din 24 Ghante         0             2003
         1551                             Road         0             2002
War      1                       Battalion 609         0             2019

              runtime    genres  imdb_rating  imdb_votes  \
genres
Action   78       160    Action          3.0       15000
         176      123    Action          2.9         304
         367      128    Action          7.1       21430
         368      128    Action          7.1       21430
         435       \N    Action          5.4           5
...               ...       ...          ...         ...
Thriller 1238     136  Thriller          3.8         112
         1246     138  Thriller          3.3          66
         1431      95  Thriller          4.0          75
         1551     134  Thriller          5.6        1099
War      1        131       War          4.1          73

                                                           story  \
genres
Action   78        Third installment of the Dabanng film series.
         176   ACP Ravindra Varma  a fearless and sincere pol...
         367   Gabbar Singh Rajput (Akshay Kumar) creates his...
         368   Gabbar Singh Rajput (Akshay Kumar) creates his...
         435   Inspector Ravi Sharma (Shamim Khan) is very ho...
...                                                          ...
Thriller 1238  Reena and fellow collegian Akash Mehta are med...
         1246  The film begins as a raunchy Bollywood sex far...
         1431  Sameera Dutta is an enlightened and intelligen...
         1551  Arvind Chauhan (Vivek Oberooi) and Lakhsmi (An...
War      1     The story revolves around a cricket match betw...

                                                         summary  \
genres
Action   78        Third installment of the Dabanng film series.
         176   ACP Ravindra Varma  a fearless and sincere pol...
         367   A grief-stricken man takes the law into his ow...
         368   A grief-stricken man takes the law into his ow...
         435   Sorry daddy is a Children story centring aroun...
...                                                          ...
Thriller 1238  Reena and fellow collegian Akash Mehta are med...
         1246  A trio of thrill-seeking housewives  plot to i...
         1431  Sameera Dutta is an enlightened and intelligen...
         1551  A couple decide to pick up a hitchhiker  but h...
War      1     The story of Battalion 609 revolves around a c...

                               tagline  \
genres
Action   78                        NaN
         176   File of Abhinay Chakra.
         367                       NaN
         368                       NaN
         435                       NaN
...                                ...
Thriller 1238                      NaN
         1246                      NaN
         1431                      NaN
         1551          Drive carefully
War      1                         NaN

                                                          actors  \
genres
Action   78    Salman Khan|Sonakshi Sinha|Sudeep|Mahesh Manjr...
         176   Govinda|Richa Sharma|Poonam Pandey|Sweta Sharm...
         367   Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...
         368   Akshay Kumar|Shruti Haasan|Kareena Kapoor|Jaid...
         435                          Shamim Khan|Mukesh Tiwari|
...                                                          ...
Thriller 1238  Bipasha Basu|Dino Morea|Preeti Jhangiani|Irrfa...
         1246  Siddharth Koirala|Aryan Vaid|Payal Rohatgi|Hin...
         1431  Rahul Bose|Ahmed Chaudhary|Nandita Das|Vineet ...
         1551  Manoj Bajpayee|Vivek Oberoi|Antara Mali|Sayaji...
War      1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...

                    wins_nominations              release_date
genres
Action   78                      NaN                       NaN
         176                     NaN     16 March 2017 (India)
         367                   1 win        1 May 2015 (India)
         368                   1 win        1 May 2015 (India)
         435                     NaN                       NaN
...                              ...                       ...
Thriller 1238                    NaN  18 February 2005 (India)
         1246                    NaN  25 February 2005 (India)
         1431                    NaN   7 November 2003 (India)
         1551  1 win & 2 nominations   27 September 2002 (USA)
War      1                       NaN   11 January 2019 (India)

[1629 rows x 18 columns]

In [227]:
# multi col.groupby
movie.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [228]:
duo = mov.groupby(['Director','Star1'])
duo

duo.get_group(('Christopher Nolan','Christian Bale'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
36,The Prestige,2006,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
63,The Dark Knight Rises,2012,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
155,Batman Begins,2005,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0

In [229]:
mov.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [231]:
duo['Gross'].sum().sort_values(ascending=False).head(3)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Anthony Russo   Joe Russo         2.205039e+09
Billy Wilder    William Holden    1.286779e+09
Name: Gross, dtype: float64

In [237]:
# find the best combo actor - gener in terms of meta score
mov.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head(3)

               Star1    Genre  Metascore
230   Ellar Coltrane    Drama      100.0
329  Humphrey Bogart    Drama      100.0
360    James Stewart  Mystery      100.0

In [243]:
duo.agg(['min','max']).head(2)

                                           Series_Title  \
                                                    min
Director     Star1
Aamir Khan   Amole Gupte               Taare Zameen Par
Aaron Sorkin Eddie Redmayne  The Trial of the Chicago 7

                                                        Released_Year        \
                                                    max           min   max
Director     Star1
Aamir Khan   Amole Gupte               Taare Zameen Par          2007  2007
Aaron Sorkin Eddie Redmayne  The Trial of the Chicago 7          2020  2020

                            Runtime       Genre        IMDB_Rating       \
                                min  max    min    max         min  max
Director     Star1
Aamir Khan   Amole Gupte        165  165  Drama  Drama         8.4  8.4
Aaron Sorkin Eddie Redmayne     129  129  Drama  Drama         7.8  7.8

                            No_of_Votes                Gross               \
                                    min     max          min          max
Director     Star1
Aamir Khan   Amole Gupte         168895  168895    1223869.0    1223869.0
Aaron Sorkin Eddie Redmayne       89896   89896  853090410.0  853090410.0

                            Metascore
                                  min   max
Director     Star1
Aamir Khan   Amole Gupte          NaN   NaN
Aaron Sorkin Eddie Redmayne      77.0  77.0

In [246]:
IPL.head(1)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [249]:
IPL.shape

(179078, 21)

In [256]:
# find the top 10 batsman in terms of runs
IPL.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [261]:
# find the batsman with max no. of sixes
six = IPL[IPL['batsman_runs']==6]
six.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(3)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
Name: batsman, dtype: int64

In [275]:
# find the bastsman with most number of 4 and 6 in last 5 over 
ov = IPL[IPL['over']>15]
# type(ov)
ov = ov[(ov['batsman_runs']==6)|(ov['batsman_runs']==4)]
ov.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(3)

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
Name: batsman, dtype: int64

In [282]:
# find kohli's record against all teams
# IPL.groupby('batsman')['batsman']
vk= IPL[IPL['batsman']=='V Kohli']
vk.groupby('bowling_team')['batsman_runs'].sum()

bowling_team
Chennai Super Kings        749
Deccan Chargers            306
Delhi Capitals              66
Delhi Daredevils           763
Gujarat Lions              283
Kings XI Punjab            636
Kochi Tuskers Kerala        50
Kolkata Knight Riders      675
Mumbai Indians             628
Pune Warriors              128
Rajasthan Royals           370
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        509
Name: batsman_runs, dtype: int64

In [287]:
# create a function that can return the heighest  score of any batsman
vk.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1)

match_id
626    113
Name: batsman_runs, dtype: int64

In [300]:
def highest(batsman):
    t_d = IPL[IPL['batsman']== batsman]
    return t_d.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]
highest('MS Dhoni')

89